# prometheus.yml
global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  # 抓取 Kafka JMX Exporter 的指标
  - job_name: 'kafka-jmx-exporter'
    scrape_interval: 30s
    scrape_timeout: 20s
    static_configs:
      - targets: ['kafka-jmx-exporter:8080']

  # 抓取 Node Exporter 的操作系统指标
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']