# Producer数量扩展性测试
name: Producer Scaling Test

topics: 1
partitionsPerTopic: 16     # 足够的分区支持多个producer
keyDistributor: "ROUND_ROBIN"
messageSize: 1024          # 固定消息大小

# 测试不同Producer数量 - 修改这个值：1, 2, 4, 8, 16
producersPerTopic: 4
producerRate: 2500         # 每个producer的速率，总速率 = producersPerTopic * producerRate

# 固定consumer配置
consumerPerSubscription: 8
subscriptionsPerTopic: 1

testDurationMinutes: 5
warmupDurationMinutes: 1