# Kafka configuration optimized for maximum throughput
name: Kafka Max Throughput
driverClass: benchmark.drivers.kafka.KafkaDriver

# Topic configuration for high throughput
replicationFactor: 1  # Lower replication for higher throughput

topicConfig: |
  cleanup.policy=delete
  compression.type=lz4

# Common settings
commonConfig: |
  bootstrap.servers=localhost:9092
  default.api.timeout.ms=120000

# Producer settings optimized for throughput
producerConfig: |
  acks=1
  linger.ms=100
  batch.size=1048576
  buffer.memory=67108864
  compression.type=lz4
  max.in.flight.requests.per.connection=5

# Consumer settings optimized for throughput
consumerConfig: |
  auto.offset.reset=earliest
  enable.auto.commit=false
  fetch.min.bytes=1048576
  fetch.max.bytes=52428800
  max.partition.fetch.bytes=10485760