# Kafka latency driver configuration
# Optimized for low latency scenarios

name: Kafka
driverClass: benchmark.drivers.kafka.KafkaDriver

# Kafka client-specific configuration
replicationFactor: 1

topicConfig: |
  min.insync.replicas=1

commonConfig: |
  bootstrap.servers=localhost:9092
  default.api.timeout.ms=120000
  request.timeout.ms=120000

producerConfig: |
  acks=all
  linger.ms=1
  batch.size=16384
  compression.type=none
  buffer.memory=33554432

consumerConfig: |
  auto.offset.reset=earliest
  enable.auto.commit=false
  fetch.min.bytes=1
  fetch.max.bytes=52428800
  max.partition.fetch.bytes=1048576