# Kafka throughput driver configuration
# Compatible with Java OpenMessaging Benchmark format

name: Kafka
driverClass: benchmark.drivers.kafka.KafkaDriver

# Kafka client-specific configuration
replicationFactor: 1

topicConfig: |
  min.insync.replicas=1
  cleanup.policy=delete
  retention.ms=604800000

commonConfig: |
  bootstrap.servers=localhost:9092
  socket.timeout.ms=120000
  api.version.request.timeout.ms=10000

producerConfig: |
  acks=all
  linger.ms=1
  batch.size=1048576
  compression.type=gzip
  queue.buffering.max.kbytes=32768
  message.max.bytes=1048576

consumerConfig: |
  auto.offset.reset=earliest
  enable.auto.commit=false
  fetch.min.bytes=1
  fetch.max.bytes=52428800
  max.partition.fetch.bytes=1048576